### ISSUE TITLE
Anisotropy example is using KHR_materials_anisotropy incorrectly

### ISSUE THREAD

**Issue by fhechtAdobe** [KhronosGroup/3D-Formats-Guidelines#21]
Hi, I was super excited to find an example of a GLTF asset with anisotropy. Especially one that is using a texture to drive the anisotropy. Thank you for making that public.

But the asset is not using the `KHR_materials_anisotropy` extension as described here: [KHR_materials_anisotropy](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_materials_anisotropy/README.md)

The asset uses this:
```
"KHR_materials_anisotropy": {
    "anisotropy": 0.75,
    "anisotropyDirection": [
        1,
        1,
        0
    ],
    "anisotropyDirectionTexture": {
        "index": 3
    }
},
```

Based on the spec there should be `anisotropyStrength`, `anisotropyRotation` (a single float value) and `anisotropyTexture`.

I suspect this asset was made with an earlier version of the extension spec, before it was ratified. If you have a version of this asset that you can publish with an updated extension that would be super valuable, so that people can see how this type of asset should be constructed.

Thanks so much!
- Florian

**Comment by echadwick-artist** [comment]
Ah thanks for finding this. This is indeed an older version of the asset. 

The current version, with correct formatting and documentation, is here: https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/AnisotropyBarnLamp

I will remove the assets in the 3D-Formats-Guidelines repo since they are needlessly duplicated here.

**Comment by echadwick-artist** [comment]
Fixed with PR22 https://github.com/KhronosGroup/3D-Formats-Guidelines/pull/22
