### ISSUE TITLE
Final naming for ArtistGuide.md and DeveloperGuide.md

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/3D-Formats-Guidelines#6]
Since we've renamed the repository to 3D-Formats-Guidelines, and may consider including other documents like [IBL best practices](https://github.com/KhronosGroup/glTF/pull/1761), I think the terms "Artist Guide" and "Developer Guide" may become ambiguous quickly. On the other hand, I don't think the filenames need to be the complete titles.

How about: `KTXArtistGuide.md` and `KTXDeveloperGuide.md`?

/cc @lexaknyazev @echadwick-wayfair

**Comment by echadwick-wayfair** [comment]
That sounds great to me.

**Comment by lexaknyazev** [comment]
Fine with me.

**Comment by donmccurdy** [comment]
Thanks, done!
